# Changes here will be overwritten by Copier
_commit: v3.2.1
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: private-assistant-switch-skill-py
github_username: stkr22
project_description: 'Home Automation Skill for Modular Private Assistant: Manages
    and controls smart plugs and bulbs via Home Assistant API.'
project_name: Private Assistant Switch Skill
publish_to_pypi: false
python_package_distribution_name: private-assistant-switch-skill
python_package_import_name: private_assistant_switch_skill
python_package_version: 1.5.0
use_containers: true
